volumes:
  pg_data_volume:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
    depends_on: 
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
      - ./frontend/:/app/result_build/
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
      