"""Константы приложения food."""
from string import ascii_letters, digits

CHARACTERS = ascii_letters + digits
TOKEN_LENGTH = 6
MAX_NAME_LENGTH = 256
MAX_NAME_LENGTH_INGREDIENT = 128
MAX_MEASUREMENT_UNIT_LENGTH = 64
MAX_NAME_LENGTH_TAG = 32
MAX_SLUG_LENGTH_TAG = 32
MAX_AMOUNT_VALUE = 32767
MIN_AMOUNT_VALUE = 1
